# Generated by Django 6.0.2 on 2026-02-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='bibliografia',
            new_name='biografia',
        ),
    ]
